all:		undirectedGraphdriver

undirectedGraphdriver:	undirectedGraphtest.cpp
		g++ -o undirectedGraphdriver -std=c++11 -g undirectedGraphtest.cpp

run:		./undirectedGraphdriver

clean:
		rm -f undirectedGraphdriver